# Generated by Django 5.1.2 on 2024-10-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(default="teste", max_length=150),
            preserve_default=False,
        ),
    ]
