# Generated by Django 5.1.2 on 2024-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_candidateprofile_personal_sumary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="email",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="phone1",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="phone2",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone1",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone2",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="vacancies",
            name="email",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="vacancies",
            name="phone1",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="vacancies",
            name="phone2",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
