# Generated by Django 5.1.2 on 2024-10-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_candidateprofile_email_candidateprofile_phone1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="vacancies",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
