# Generated by Django 5.1.2 on 2024-10-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_candidateprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
