# Generated by Django 5.1.2 on 2024-10-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_companyprofile_company_name_savevacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vacancies",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
